language: node_js
node_js:
- '10.14'
cache:
  directories:
  - $HOME/.cache/yarn
  - node_modules
  - dist
addons:
  chrome: stable
before_install:
- npm i -g yarn
- yarn -v
install:
- yarn
script:
- yarn test
- yarn build @lashar/ng-lazyload
before_deploy:
- cd dist/lashar/lazyload
deploy:
  provider: npm
  email: mehdi.daneshvar@live.co.uk
  skip_cleanup: true
  api_key:
    secure: Aa0ui3+S1ggHHa480QkTtrnvdR742XErwiS24KuAWe7LFDVlqyK3FLCrX9lqv81XlMcHb6CVNMpl5ihKohvQCjMqD2CsS/gQ2Q+RLjL15X0QZ5F9rRoKNsBit/G97LrqaRZOqsgbmn/OGKS8XQTb4UXMNSRISspP63eQTfDQVyHj4v/67TzU9gm2Z+Hs/FOo2pzW8CLmupTXqIjcItg6xboQ/XUE4Z8AMZXn5gY9kuTr/eZtZ6AJM5SzkNrav/LC/qguqY/9LsHknAgtyO6Z4x3CmtIjrm7oBgbCGBU5tUx0Ozcx6d0uAVS1tEV3L7qbRXG7QRXDhqWmYVkKmqdX+I4xtk7zGMrHnhVUXow21Z9SC1Q7qzJE35EI8yC+m8jmPErZ2Xyvj2C5PCsnQLBJeCha3DxV23RpiV0yyWP1c+cnvBvlLXkN435+ehaFfsXIw6cXpCVADPDCFRPfvBkaGFimKJ5ZuRqhV8xgjxmubn/7wFCygpyKaiWJMK8gQ37PYqEO8cgz3Iv1UrJUlFoqsoyoALbn5IIpczCI0auffTB8pb3qcE9qlkSDY3gKUaAZrGDJ1sCycRTjVmCoErWh2aYu2g1sk7y/RLc8dmm6+Nxn2gx3/btWKjXNeBY3YuS7T6gw0OahBZ7v2IvsN9fArIEvbmC2eIUJygyUzhSxjsU=
  on:
    tags: true
